---
title: "Necrosis Project Figures"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: html_document
---

### Load Packages
This code chunk loads the relevant packages for creating figures 
```{r, echo=FALSE}
library(tidyverse)
library(readxl)
```

### Load Data

```{r}
df_injury <- read_xlsx("data/Control Group Data_Model Ver.xlsx",
                    sheet="Clinical Onset of Injury Pheno", range="A1:K36") |> 
  janitor::clean_names() |> 
  drop_na(animal_id) |> 
  rename(erythema_start = erythema_day_7, desquamation_start = desquamation, 
         desquamation_end = desquam_end, ulceration_start = ulceration, ulceration_end = ulc_end,
         necrosis_start = necrosis, necrosis_end = necro_end) |> 
  mutate(wound_id = paste0(animal_id, "_", skin_site)) |> 
  select(wound_id, animal_id, skin_site, sex, ends_with("_start"), ends_with("_end")) |> 
  pivot_longer(erythema_start:necrosis_start,
               names_to = "wound_type", names_pattern = "(.*)_start", values_to = "wound_start") |> 
  pivot_longer(erythema_end:necrosis_end,
               names_to = "wound_type2", names_pattern = "(.*)_end", values_to = "wound_end") |> 
  filter(wound_type == wound_type2) |> 
  select(-wound_type2)
```



```{r}
df_duration <- tibble(
  tx = c(rep("A", 50), rep("B", 50)),
  start = c(rnorm(50, 4, 2), rnorm(50, 6, 3)),
  duration = rnorm(100, 7, 5),
  end = start + duration
) 
```



```{r}
df_injury |> 
  group_by(wound_type) |> 
  summarize(avg_start = mean(wound_start), 
            sem_start = sd(wound_start)/sqrt(n()),
            avg_end = mean(wound_end),
            sem_end = sd(wound_end)/sqrt(n())
            ) |> 
  ggplot() +
  geom_rect(aes(xmin = avg_start, xmax = avg_end, 
                ymin = as.numeric(factor(wound_type)) - 0.3, 
                ymax = as.numeric(factor(wound_type)) + 0.3, 
                fill = wound_type), 
            color = "black", alpha=0.8) +
  geom_errorbar(aes(xmin = avg_start - sem_start, xmax = avg_start, y = wound_type), width = 0.2)+
  geom_errorbar(aes(xmin = avg_end, xmax = avg_end + sem_end, y = wound_type), width = 0.2) +
  theme_bw() +
  labs(
    x = "Days after exposure",
    y = "Treatment Group",
    color = "Treatment"
  )
```

